locale: "en-US"
site_theme: "default"

title: "K.P Singh"
title_separator: "-"
name: "Kamal Preet Singh"
position: "Assistant Professor"
affiliation: "Swami Rama Himalayan University, Dehradun, India"
email: "kamalpreet1010@gmail.com"
baseurl: ""
keywords: "Kamalpreet Singh, KP Singh, AI researcher India, Machine Learning professor India"

description: "Official website of Kamal Preet Singh (KP Singh), Assistant Professor specializing in Artificial Intelligence, Machine Learning, Data Science and Cybersecurity."

url: "https://kpsingh.in"
repository: "kaypee1010.github.io"

author:
  name   : "Kamal Preet Singh"
  avatar : "profile.png"
  bio    : "Assistant Professor | AI/ML| Data Science<br><strong>Swami Rama Himlayan University, Dehradun, India</strong>"
  googlescholar: "https://scholar.google.com/citations?user=vxEyeVMAAAAJ"
  orcid: "https://orcid.org/0000-0001-7949-0767"
  scopus: "https://www.scopus.com/authid/detail.uri?authorId=56688926400"
  linkedin: "kaypee-singh"
  github: "/in/kaypee-singh/"

  academic_cv: "/files/cv/academic_cv.pdf"
  industry_resume: "/files/cv/industry_resume.pdf"
  publications_page: "/publications/"
  talks_page: "/talks/"

  

social:
  links:
    - https://github.com/kaypee1010
    - https://orcid.org/0000-0001-7949-0767
    - https://scholar.google.com/citations?user=vxEyeVMAAAAJ
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

include:

- .htaccess
- _pages
- files
