locale: "en-US"
site_theme: "default"

title: "K.P"
title_separator: "-"
name: "Kamal Preet Singh"
position: "Assistant Professor"
affiliation: "Swami Rama Himalayan University, Dehradun, India"
email: "kamalpreet1010@gmail.com"
baseurl: ""

description: "Assistant Professor specializing in Artificial Intelligence, Machine Learning, Data Analytics, and Cybersecurity with academic and industry experience across India and Australia."

url: "https://kaypee1010.github.io"
repository: "kaypee1010.github.io"

author:
  name   : "Kamal Preet Singh"
  avatar : "profile.png"
  bio    : "Assistant Professor | AI/ML| Data Science<br><strong>Swami Rama Himlayan University, Dehradun, India</strong>"
  googlescholar: "https://scholar.google.com/citations?user=vxEyeVMAAAAJ"
  orcid: "https://orcid.org/0000-0001-7949-0767"
  scopus: "https://www.scopus.com/authid/detail.uri?authorId=56688926400"
  linkedin: "kaypee-singh"
  github: "kaypee1010"
  



include:

- .htaccess
- _pages
- files
